import { apiGet, apiPost, apiPut } from './http';
import type { DemoDataSeedResult, DemoModeStatus, SmtpSettings, SmtpTestResult, UserCaptcha } from '@/types/api';

export const adminApi = {
  getLoginCaptcha: () => apiGet<UserCaptcha>('/api/v1/admin/auth/captcha'),
  login: (payload: Record<string, unknown>) => apiPost<any>('/api/v1/admin/auth/login', payload),
  me: () => apiGet<any>('/api/v1/admin/auth/me'),
  getDashboardOverview: () => apiGet<any>('/api/v1/admin/dashboard/overview'),
  getOrderTrends: (params?: Record<string, unknown>) => apiGet<any[]>('/api/v1/admin/dashboard/order-trends', { params }),
  getItemStatus: () => apiGet<any[]>('/api/v1/admin/dashboard/item-status'),
  getRecentActivities: (params?: Record<string, unknown>) => apiGet<any[]>('/api/v1/admin/dashboard/recent-activities', { params }),
  getCategorySalesRanking: (params?: Record<string, unknown>) => apiGet<any[]>('/api/v1/admin/dashboard/category-sales-ranking', { params }),
  getHotKeywords: (params?: Record<string, unknown>) => apiGet<any[]>('/api/v1/admin/dashboard/hot-search-keywords', { params }),
  getUserGrowth: (params?: Record<string, unknown>) => apiGet<any[]>('/api/v1/admin/dashboard/user-growth-trends', { params }),
  getDemoModeStatus: () => apiGet<DemoModeStatus>('/api/v1/admin/demo-mode'),
  seedDemoData: () => apiPost<DemoDataSeedResult>('/api/v1/admin/demo-mode/seed'),
  updateDemoMode: (payload: { demoModeEnabled: boolean; demoItemNotesEnabled: boolean }) => apiPut<DemoModeStatus>('/api/v1/admin/demo-mode', payload),
  getSmtpSettings: () => apiGet<SmtpSettings>('/api/v1/admin/system/smtp'),
  updateSmtpSettings: (payload: Record<string, unknown>) => apiPut<SmtpSettings>('/api/v1/admin/system/smtp', payload),
  sendSmtpTestEmail: (payload: Record<string, unknown>) => apiPost<SmtpTestResult>('/api/v1/admin/system/smtp/test', payload),
  getRegistrations: (params?: Record<string, unknown>) => apiGet<any>('/api/v1/admin/registration-applications', { params }),
  getRegistrationDetail: (applicationId: number) => apiGet<any>(`/api/v1/admin/registration-applications/${applicationId}`),
  approveRegistration: (applicationId: number, payload: Record<string, unknown>) => apiPost<any>(`/api/v1/admin/registration-applications/${applicationId}/approve`, payload),
  rejectRegistration: (applicationId: number, payload: Record<string, unknown>) => apiPost<any>(`/api/v1/admin/registration-applications/${applicationId}/reject`, payload),
  getUsers: (params?: Record<string, unknown>) => apiGet<any>('/api/v1/admin/users', { params }),
  getUserDetail: (userId: number) => apiGet<any>(`/api/v1/admin/users/${userId}`),
  updateUserStatus: (userId: number, payload: Record<string, unknown>) => apiPost<any>(`/api/v1/admin/users/${userId}/status`, payload),
  getItems: (params?: Record<string, unknown>) => apiGet<any>('/api/v1/admin/items', { params }),
  getItemDetail: (itemId: number) => apiGet<any>(`/api/v1/admin/items/${itemId}`),
  updateItemStatus: (itemId: number, payload: Record<string, unknown>) => apiPost<any>(`/api/v1/admin/items/${itemId}/status`, payload),
  getOrders: (params?: Record<string, unknown>) => apiGet<any>('/api/v1/admin/orders', { params }),
  getOrderDetail: (orderId: number) => apiGet<any>(`/api/v1/admin/orders/${orderId}`),
  cancelOrder: (orderId: number, payload: Record<string, unknown>) => apiPost<any>(`/api/v1/admin/orders/${orderId}/cancel`, payload),
  closeOrder: (orderId: number, payload: Record<string, unknown>) => apiPost<any>(`/api/v1/admin/orders/${orderId}/close`, payload),
  getAnnouncements: (params?: Record<string, unknown>) => apiGet<any>('/api/v1/admin/announcements', { params }),
  getAnnouncementDetail: (announcementId: number) => apiGet<any>(`/api/v1/admin/announcements/${announcementId}`),
  createAnnouncement: (payload: Record<string, unknown>) => apiPost<any>('/api/v1/admin/announcements', payload),
  updateAnnouncement: (announcementId: number, payload: Record<string, unknown>) => apiPut<any>(`/api/v1/admin/announcements/${announcementId}`, payload),
  publishAnnouncement: (announcementId: number, payload: Record<string, unknown>) => apiPost<any>(`/api/v1/admin/announcements/${announcementId}/publish`, payload),
  offlineAnnouncement: (announcementId: number, payload: Record<string, unknown>) => apiPost<any>(`/api/v1/admin/announcements/${announcementId}/offline`, payload)
};